version: '3.0'
services:

  traefik:
    image: traefik:1.7
    command: --web --docker --docker.domain=app.test --logLevel=DEBUG
    ports:
    # access this with the correct Host header to access the respective container
    - "80:80"
    # management UI
    - "8080:8080"
    - "443:443"
    volumes:
    # traefik does its magic by reading information about running containers from the docker socket
    # - /var/run/docker.sock:/var/run/docker.sock
    # - /dev/null:/traefik.toml
    - ./traefik.toml:/etc/traefik/traefik.toml:ro
    #- ~/ssl:/etc/traefik/ssl:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./acme.json:/etc/acme.json
    networks:
      default:

networks:
  default:
    external:
      name: traefik_net
