version: '3.5'
services:

  # app3, app4 are Caddy instances listening to port 80 and serving an index.html.
  app3:
    build:
      context: .
      dockerfile: app3-Dockerfile
    networks:
      internal-network:
        # the aliases are not required, but are useful if the applications want to internally
        # reference each other by host name
        aliases:
        - "app3.test"
    labels:
    - "traefik.port=80"
    - "traefik.frontend.rule=Host:app3.test"

  app4:
    build:
      context: .
      dockerfile: app4-Dockerfile
    networks:
      internal-network:
        aliases:
        - "app4.test"
    labels:
    - "traefik.port=80"
    - "traefik.frontend.rule=Host:app4.test"
networks:
  internal-network:
    internal: true

